[package]
name = "thread-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
affinity = "0.1.2"
crossbeam = "0.8.4"
go-spawn = "0.1.2"
num_cpus = "1.0"
num_threads = "0.1.7"
rayon = "1.10.0"
send_wrapper = "0.6.0"
thread-amount = "0.1.3"
thread-control = "0.1.2"
thread-priority = "1.1.0"
