[package]
name = "async-await-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
futures = { version = "0.3.30", features = ["thread-pool"] }
futures-lite = "2.3.0"
smol = "2.0.0"
tokio = { version = "1.39.2", features = ["full"] }
